version: '3.8'
services:
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "50050:50050"
    deploy:
      replicas: 1
    depends_on:
      - kafka
      - order-dispatcher
  order-dispatcher:
    build:
      context: ./order-dispatcher
    container_name: order-dispatcher
    ports:
      - "50051:50051"
    depends_on:
      - kafka
  order-service:
    build:
      context: ./order-service
    depends_on:
      - kafka
    deploy:
      replicas: 3
  order-generator:
    build:
      context: ./ordergen
    depends_on:
      - kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "orders:3:1"
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:
  zookeeper-data: