#Thu Dec 26 17:33:19 UTC 2024
micronaut:
  application:
    name: payment-service
kafka:
  bootstrap:
    servers: kafka:9092
  consumers:
    default:
      group-id: payment-service-group
      auto-offset-reset: earliest

